import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import MobileNav from "@/components/MobileNav";
import DesktopNav from "@/components/DesktopNav";
import ThemeObserver from "@/components/ThemeObserver";
import LoginInterface from "@/components/LoginInterface";

import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black`}
      >
        <Theme>
          {modal}

          <div className="flex min-h-screen dark:bg-gray-950 dark:text-gray-300">
            <DesktopNav />
            <div className="pb-24 lg:pb-4 pt-4  px-4 lg:px-8 w-full  flex justify-around ">
              {session && <div className="w-full">{children}</div>}
              {!session && <LoginInterface />}
            </div>
          </div>

          <MobileNav />
        </Theme>
        <ThemeObserver />
      </body>
    </html>
  );
}
